### ISSUE TITLE
Add new value, "Pending" to servicerequestresponses model; set that as default request_response value for all new service requests

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/whispersservices_django#282]
Related to https://github.com/USGS-WiM/whispers/issues/704

**Comment by aaronstephenson** [comment]
Implemented in 1.3.6 3c3fa66

**Comment by BlakeDraper** [comment]
@aaronstephenson this appears not to be pushed to the dev server yet? I just created a new service request and response is coming back as `null`. Can you go ahead and push this to dev for testing?

**Comment by aaronstephenson** [comment]
It's on the dev server. What value are you sending for that field? It's a nullable field, so if you're sending null or null equivalent, that's what you'll get back in the response. To make it use the default of "Pending", don't send the field.

Otherwise I will need to change the code so that the field is no longer nullable but defaults to "Pending".

**Comment by aaronstephenson** [comment]
Ugh, it was the same issue as on test/prod: The "Pending" record was not in the whispers_servicerequestresponse DB table. :headdesk:

So, I just added that record to the dev DB (it was already in the test and prod DBs). It should work on the dev server now.

**Comment by BlakeDraper** [comment]
Looks good now, thanks 👍
