### ISSUE TITLE
Exposed tables via API

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices_django#294]
There are a few tables that should not be available through the web API (both test and live) as I was able to access not logged in or as a non-admin user.  I'm still combing through, but these jumped out at me:
1. Comments
2. Servicerequests
3. Staff
4. EventContacts (there's no code list, but would be good to hide.  legacy data)
5. EventLocationContact (this should be permission based.  again no code list though)
6. Roles (Lower priority, I understand this probably needed for registration form.  Just wondering if we could hide)

**Comment by aaronstephenson** [comment]
Thanks Neil.

I've had Servicerequests and Comments on my TODO list for a while, but Comments is a really problematic model since it uses generic relations. A stop-gap I've been thinking about is just allowing access for comment owners and org members until I can devote time to the issue. Note that this would just be for the `/comments/` endpoint, not comments that would appear in Event details, etc, since the permissions for those end points are far easier to handle and already work.

I think Roles needs to remain publicly readable, otherwise an API user would never know what role to choose when requesting a role change.

**Comment by aaronstephenson** [comment]
@nbaertlein I pretty much have this done, but want to get one more bit of clarification from you first. Here's how I have the permissions set in my latest changes, let me know if I should alter any:

1. Comments: Admins see all, Partners see their own/their org's/their collaboration events', anyone else sees an empty list
2. ServiceRequests: Admins see all, Partners see their own, anyone else sees an empty list (this one is probably not right?)
3. Staff: Admins see all, anyone else sees an empty list
4. EventContacts: Admins see all, anyone else sees an empty list
5. EventLocationContacts: Admins see all, Partners see their own/their org's/their collaboration events', anyone else sees an empty list
6. Roles: anyone can see the whole list (only Admins can edit tho)

**Comment by nbaertlein** [comment]
@aaronstephenson 
Looks good except for 1 small tweak as you suggested:
2. Service Requests:  This can be the same as No.5 in this list, which is based on the overall permissions to the event.

**Comment by aaronstephenson** [comment]
Fixed in 1.4.1 86480e9
