### ISSUE TITLE
error on POST to alert_collaborators

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/whispersservices_django#346]
The user is a read collaborator.

Postman:
![image](https://user-images.githubusercontent.com/23640741/76132052-f66df080-5fde-11ea-9b41-bda54f343a04.png)

Client:
![image](https://user-images.githubusercontent.com/23640741/76132117-4c429880-5fdf-11ea-8751-08e1bc5352c6.png)

**JSON**:
```
{
  "event": "170737",
  "recipients": [
    21
  ],
  "comment": "f"
}
```

**Response**:
```
{
    "detail": "One or more submitted recipient IDs are not eligible to receive alerts about this event. Eligible recipients are collaborators of this event or users in the same organization as the creator of this event, or system administrators."
}
```

**Comment by aaronstephenson** [comment]
Fixed in 69ca13a9

Looks like I confused myself when reading the "WHISPers Notification Reference with NWHC text" spreadsheet. Only "qualified" users (those who can edit a particular event) can create alerts, and I was using that list to validate the recipients list also, forgetting that read collaborators can also receive alerts (just not create them).
