### ISSUE TITLE
direct users to section updated?

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#356]
Are we going to be able to fill in what main section of the event was updated? At one point, it seemed Aaron thought that'd be easy enough. But if it's not happening, then we'll edit this text so that the line "Updates were made to the following sections:" is removed.

![image](https://user-images.githubusercontent.com/49287076/77450762-bcb02e80-6dc1-11ea-8a45-a92e3a3eff34.png)

**Comment by aaronstephenson** [comment]
I actually said the opposite 🙁 Looking up the specific fields on specific models is doable but will require a fair amount of work.

**Comment by JChipault** [comment]
what about just identifying general sections like location, species, diagnosis?

**Comment by aaronstephenson** [comment]
That's pretty much the same thing. The difficulty lies in having to traverse several levels of relationships, and trying to optimize those queries so they don't bog down the server.

We're not saying we won't eventually implement this, just that due to the difficulty and the myriad other tasks we have, we consider this to be lower priority.

**Comment by aaronstephenson** [comment]
Full update information has been included in notifications for a while now.
