### ISSUE TITLE
custom notification fields and values

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispersservices_django#366]
How hard would it be to make the fields and criteria paired in this messaging such that it reads "Affected Count: <= 10, State: California, Species: Mallard, Diagnosis: Botulism"? This would not only make it easier to read, but make the text on the notification match how the user sees it displayed in notification settings.

![image](https://user-images.githubusercontent.com/49287076/78268884-7b5d0480-74ce-11ea-92da-7134d6c80ae1.png)

![image](https://user-images.githubusercontent.com/49287076/78269119-c1b26380-74ce-11ea-98d8-73177aea5797.png)

**Comment by aaronstephenson** [comment]
I can do it but it will take some work. The current format adheres to what you wrote for the notification message template. Do you want me to change the template on my own or do you want to change it?

**Comment by aaronstephenson** [comment]
If you don't object, I think I will proceed like this:

Instead of the current `<p>Your Custom Notifications are set for {new_updated} Events with {field}: {criteria}.</p>`
where `{field}` is the left had side of the search and `{criteria}` is the right hand side, I will do it like this: `<p>Your Custom Notifications are set for {new_updated} Events with:</p><div>{criteria}</div><br />`
where `{criteria}` will contain the entire search string and be formatted similar to how it's presented in the web client application (with new lines for each criterion within the div, e.g. `<p>Affected Count: <= 10</p><p>State: California</p><p>Species: Mallard</p><p>Diagnosis: Botulism</p>`).

**Comment by JChipault** [comment]
Thanks, that sounds good. Sorry that we didn't set it up in the notifications spreadsheet with an example of what we pictured for multiple fields!
