### ISSUE TITLE
No stale event notification

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispersservices_django#385]
We have not received any stale event notifications.  Notification period configuration was recently updated to 1, 2, & 5 days, but still haven't seen anything.

**Comment by aaronstephenson** [comment]
This was caused by a combination of two things:

1. The configuration value for the `stale_event_periods` record was in the wrong format; the value should be a plain string, with a series of values being represented as a string with comma separators (e.g., `1,2,5`), but the value that was actually in the cell was `[1,2,5]` . The latter is the proper way to write a list in python, but in this case the python code just needs to read a raw string, which it then coerces into a list if necessary (in other words, the code is expecting a string, not a list).
2. The date math was using the wrong operators (it had >= instead of <=)

The solution to the first problem was to just change the value in the database. The solution to the second problem was implemented in 6a5d4cd5
